services:
  - type: web
    name: springboot-calculator
    runtime: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SERVER_PORT
        value: 8081
